### ISSUE TITLE
Add get_wholesomememe()

### ISSUE THREAD

**Issue by dinhanhx** [Huy-Ngo/reddit-meme-api#1]
To get memes from this subreddit [r/wholesomememes](https://www.reddit.com/r/wholesomememes/) 

If it's possible, please get the one that reaches [r/all](https://www.reddit.com/r/all/)

Relevant issue [discord meme bot issue #2](https://github.com/Huy-Ngo/discord-meme-bot/issues/2)

**Comment by Huy-Ngo** [comment]
The route `/memes/<subreddit>` already covers this.
